spring:
  datasource:
    url: jdbc:h2:file:./LOCAL_DATA/H2/mycitygov2db;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driverClassName: org.h2.Driver
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  h2:
    console:
      enabled: true
      path: /h2-console

server:
  port: 8080

logging:
  level:
    org.hibernate.SQL: debug
    org.springframework.security: DEBUG

routee:
  app-id: 5bba56ece4b0a43fbf239aae
  app-secret: kDsvtwHe3w
  sender: HUANOC

mycitygov:
  mockgov:
      api-base-url: "http://localhost:8091"
      public-base-url: "http://localhost:8091"
      client-token: "mycitygov-client-token"

  noc:
    base-url: "http://localhost:8081"
    sms:
      active: true
  storage:
    s3:
      endpoint: "http://localhost:9000"
      access-key: "minioadmin"
      secret-key: "minioadmin"
      bucket: "mycitygov"
      region: "us-east-1"

